title: Finance Pebble
description: My personal blog where I share thoughts and ideas about finance
author: Finance
email: financepebble101@gmail.com
url: "https://financepebble.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: "/page:num/"

# SEO
lang: en
